### ISSUE TITLE
what is lambda-list-keywords in define-rpc-method

### ISSUE THREAD

**Issue by imnisen** [mmontone/trivial-rpc#1]
Hi,  I wonder what is  `lambda-list-keywords` in the definition of  `define-rpc-method`as following:
```
(defmacro define-rpc-method (method ((self class stub) &rest args)
                                    &body body)
  (let ((argnames (loop for x in args
                        if (listp x) collect (car x) else
                        unless (find x lambda-list-keywords) collect x)))   ;; <-- here
    `(prog1 (defmethod ,method ((,self ,class) ,@args) ,@body)
       (defmethod ,method ((,self ,stub) ,@args)
         (let ((transport (slot-value ,self 'transport)))
           (send-packet transport (cons ',method (list ,@argnames)))
           (lambda () (recv-packet transport)))))))
```

**Comment by mmontone** [comment]
Looks like a clear error to me. I got it from here, though: http://cl.kozachuk.info/2011/09/extendable-asynchronous-rpc-framework.html.

I'm not maintaining this code at the moment, sorry.

**Comment by imnisen** [comment]
@mmontone  I think I find what `lambda-list-keywords` is:

from [Hyperspec](http://clhs.lisp.se/Body/v_lambda.htm)

> a list, the elements of which are implementation-dependent, but which must contain at least the symbols &allow-other-keys, &aux, &body, &environment, &key, &optional, &rest, and &whole.

**Comment by mmontone** [comment]
:+1:
